### PR TITLE
fixed config

### PR DESCRIPTION
**Pull request by emravera**

### CODE REVIEW

**Comment by cgadam** [comment]
@emravera you should turn this repo into private! I'm still able to see it 👅  👀

**Comment by albertinad** [comment]
@cgadam we can't! This is a fork of a public repo so it must remain public

**Comment by emravera** [comment]
As @albertinad said we can't. Is one of our contributions to the open source world. 😄

**Comment by horaciovinuesa** [comment]
Nice, thanks for the contribution guys !

**Pull request merged**
